openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: API documentation for my project

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /users/{id}:
    get:
      summary: Get a user by ID
      description: Retrieve user details.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user's unique ID.
      responses:
        200:
          description: User data retrieved successfully.
        404:
          description: User not found.
        500:
          description: Server error.
